services:
  - type: web
    name: php-app
    env: php
    plan: free
    buildCommand: "" # No specific build step required for PHP
    startCommand: php -S 0.0.0.0:8080 -t public
    staticPublishPath: public
